--- 
user: mongrel_tubemarks
group: app_tubemarks
cwd: /opt/apps/tubemarks/current
log_file: /opt/apps/tubemarks/shared/log/mongrel.log
port: "8010"
environment: production
address: 127.0.0.1
pid_file: /opt/apps/tubemarks/shared/pids/mongrel.pid
servers: 1